title    Solara Linux (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-solara-kernel
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-solara-kernel.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
