title    Solara Linux (%ARCH%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-solara-kernel
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-solara-kernel.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% accessibility=on
