modules-search: [ global, local ]

# branding: which branding component to use
# This should be the name of the subdirectory in
# /etc/calamares/branding or in the branding directory
# shipped with Calamares in share/calamares/branding/
branding: solara

# If true, Calamares will show an "Are you sure?" prompt before
# actually starting the installation. Default is false.
# showUnmountConfirmation: true

# If true, Calamares will use the default desktop environment for
# switching to the new system when it's done. Default is false.
# (this is useful for live images)
# showSudoersConfirmation: false

# If true, the "Select language" step can be skipped. If set to false,
# "Select language" will be shown only if there are fewer than 2
# languages available. Default is true.
# showSkipLanguageSelection: false

# If true, the "User account" step can be skipped. If set to false,
# "User account" will always be shown. Default is false.
# showSkipUserConfirmation: false

# If true, the user has to select a timezone in the "Timezone" step.
# Default is true. If this is false, the timezone is set to UTC.
# showTimeZone: true

# If true, the "Keyboard layout" step can be skipped. If set to false,
# "Keyboard layout" will always be shown. Default is true.
# showKeyboardLayout: false

# sequence:
# The sequence is a list of module names (in the order they are
# executed). A sequence must contain at least one module, and it
# must be a valid list. The default sequence is the list of all
# available modules. For a full list of modules, see the Modules
# section of this manual.
sequence:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
  - install
  - finished

# module-backend: what backend to use for module loading
# Possible values:
#   - process  - load each module as a separate process
#               (this is the default)
#   - static   - load all modules statically (if enabled in
#               the build)
module-backend: process

# execution:
# The execution mode is a map of module names to one of four
# execution modes. The four execution modes are:
#  - execpin      - run in a separate process and wait for it to
#                  finish (the default)
#  - execnoop     - do not run at all
#  - execfork     - run in a separate process in the background
#  - external    - run in a separate process *with* interactive
#                  user input (only if the module supports it)
# The execution mode for a module can be set by using a map with the
# module name as key, e.g.
#   execution:
#       users: execnoop
#       partition: external
# This will skip the users module and run the partition module
# interactively.
execution:
  welcome: execnoop

# Configuration for the individual modules. Each key is the name of
# a module, and the corresponding value is a map of configuration
# keys for that module. The valid configuration keys for each module
# are described in the Modules section.
# modules:
#     partitioning:
#         ensureSuspend: false
#     package-manager:
#         backend: apt
#     packages:
#         ignore_order: true